/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    screens: {
      minMobile: { min: '320px', max: '520px' },
      aboveMinMobile: { min: '521px', max: '767px' },
      mobileMax: { min: '320px', max: '767px' },
      betweenMobileTab: { min: '768px', max: '1200px' },
      betweenMdDesk: { min: '1200px', max: '1480px' },
      laptopMax: { min: '320px', max: '1023px' },
      lieTablets: { min: '768px', max: '1023px' },
      aboveLaptop: { min: '1024px', max: '1201px' },
      largeDesk: { min: '1024px', max: '1360px' },
      mobileToDesk: { min: '320px', max: '1150px' },
      lieExactTab: { min: '320px', max: '1025px' },
      padPro: { min: '1024px', max: '1366px' },
      desktop: '1201px',
      desktopMd: '1400px',
      desktopLg: '1600px',
      tab: '768px',
      miniLaptop: '920px',
      belowTab: '990px',
      laptop: '1025px',
      exactLaptop: '1024px',
    },
    extend: {
      colors: {
        purple: '#4F4281',
        white: '#fff',
        blue: '#1C49CF',
        lightBlue: '#4441EB',
        darkBlue: '#2808A7',
        skyBlue: '#298AE4',
        sky: '#40C9E7',
        normalGray: '#454545',
        greenish: '#4BE4DB',
        lightGreen: '#53FFCA',
        lightGray: '#C6D4ED',
        mapGray: '#F5F9FF',
        linkBlue: '#1890FF',
        gray: '#666666',
        black: '#000',
        white: '#fff',
        skeleton: '#EBECEF',
        borderColor: 'rgba(53, 144, 194, 0.27)',
        buttonColor: '#56F1A4',
        footerPurple: '#846ddc',
        footerbg: '#2909a7',
        close: '#D7E1F2',
        grayBorder: '#E8E8E8',
        closeHover: '#C6D4ED',
        scroll: '#4F428180',
        buttonOverlay: '#E7F3FF',
        lightBlueText: '#5879aa',
        landingBlue: '#3850c1',
        blueHover: '#CEE6FF',
        themeBlue: '#03008a',
        skyBlue: '#63c0bd',
        defaultLink: '#1779ba',
        overlay: 'rgba(0, 0, 0, 0.5)',
        menu: '#575662',
        cardText: '#696e76',
        cardHeading: '#0a0a0a',
        blackOverlay: 'rgba(0,0,0, 0.1)',
        blackHighOpacity: 'rgba(0,0,0, 0.4)',
        blackDarkOpacity: 'rgba(0,0,0, 0.5)',
        danger: '#ff0000',
        success: '#008000a3',
        placeholder: '#CCCCCC',
        emptyState: '#dedede',
        blueBorder: '#81A0EC',
        graybg: "#ebf0f7",
        skyBg: "#f1f6fb",
        normalText: "#828282",
        baseBlue: "#263AAD"
      },
      fontSize: {
        xs: '12px',
        xsmall: '14px',
        small: '16px',
        midSmall: '17px',
        xmedium: '18px',
        medium: '20px',
        odd: '23px',
        xlg: '30px',
        lg: '40px',
        large: '53px',
        xlarge: '65px',
        xxlarge: '80px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
