// this data contains extra countries and old continent representations
export const countries = [
  {
    name: "Aksai Chin",
    code: null,
    continent: "Asia",
    country_iso: null,
  },
  {
    name: "Afghanistan",
    code: "AF",
    continent: "Asia",
    country_iso: "AFG",
  },
  {
    name: "Albania",
    code: "AL",
    continent: "Europe",
    country_iso: "ALB",
  },
  {
    name: "Algeria",
    code: "DZ",
    continent: "Africa",
    country_iso: "DZA",
  },
  {
    name: "American Samoa",
    code: "AS",
    continent: "Oceania",
    country_iso: "ASM",
  },
  {
    name: "Andorra",
    code: "AD",
    continent: "Europe",
    country_iso: "AND",
  },
  {
    name: "Angola",
    code: "AO",
    continent: "Africa",
    country_iso: "AGO",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    continent: "North America",
    country_iso: "ATG",
  },
  {
    name: "Argentina",
    code: "AR",
    continent: "South America",
    country_iso: "ARG",
  },
  {
    name: "Armenia",
    code: "AM",
    continent: "Asia",
    country_iso: "ARM",
  },
  {
    name: "Aruba",
    code: "AW",
    continent: "North America",
    country_iso: "ABW",
  },
  {
    name: "Australia",
    code: "AU",
    continent: "Oceania",
    country_iso: "AUS",
  },
  {
    name: "Austria",
    code: "AT",
    continent: "Europe",
    country_iso: "AUT",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    continent: "Asia",
    country_iso: "AZE",
  },
  {
    name: "Bahamas",
    code: "BS",
    continent: "North America",
    country_iso: "BHS",
  },
  {
    name: "Bahrain",
    code: "BH",
    continent: "Asia",
    country_iso: "BHR",
  },
  {
    name: "Bangladesh",
    code: "BD",
    continent: "Asia",
    country_iso: "BGD",
  },
  {
    name: "Barbados",
    code: "BB",
    continent: "North America",
    country_iso: "BRB",
  },
  {
    name: "Belarus",
    code: "BY",
    continent: "Europe",
    country_iso: "BLR",
  },
  {
    name: "Belgium",
    code: "BE",
    continent: "Europe",
    country_iso: "BEL",
  },
  {
    name: "Belize",
    code: "BZ",
    continent: "North America",
    country_iso: "BLZ",
  },
  {
    name: "Benin",
    code: "BJ",
    continent: "Africa",
    country_iso: "BEN",
  },
  {
    name: "Bermuda",
    code: "BM",
    continent: "North America",
    country_iso: "BMU",
  },
  {
    name: "Bhutan",
    code: "BT",
    continent: "Asia",
    country_iso: "BTN",
  },
  {
    name: "Bolivia",
    code: "BO",
    continent: "South America",
    country_iso: "BOL",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    continent: "Europe",
    country_iso: "BIH",
  },
  {
    name: "Botswana",
    code: "BW",
    continent: "Africa",
    country_iso: "BWA",
  },
  {
    name: "Brazil",
    code: "BR",
    continent: "South America",
    country_iso: "BRA",
  },
  {
    name: "Brunei Darussalam",

    code: "BN",
    continent: "Asia",
    country_iso: "BRN",
  },
  {
    name: "Bulgaria",
    code: "BG",
    continent: "Europe",
    country_iso: "BGR",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    continent: "Africa",
    country_iso: "BFA",
  },
  {
    name: "Burundi",
    code: "BI",
    continent: "Africa",
    country_iso: "BDI",
  },
  {
    name: "Cambodia",
    code: "KH",
    continent: "Asia",
    country_iso: "KHM",
  },
  {
    name: "Cameroon",
    code: "CM",
    continent: "Africa",
    country_iso: "CMR",
  },
  {
    name: "Canada",
    code: "CA",
    continent: "North America",
    country_iso: "CAN",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    continent: "Africa",
    country_iso: "CPV",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    continent: "North America",
    country_iso: "CYM",
  },
  {
    name: "Central African Republic",
    code: "CF",
    continent: "Africa",
    country_iso: "CAF",
  },
  {
    name: "Chad",
    code: "TD",
    continent: "Africa",
    country_iso: "TCD",
  },
  {
    name: "Chile",
    code: "CL",
    continent: "South America",
    country_iso: "CHL",
  },
  {
    name: "China",
    code: "CN",
    continent: "Asia",
    country_iso: "CHN",
  },
  {
    name: "Colombia",
    code: "CO",
    continent: "South America",
    country_iso: "COL",
  },
  {
    name: "Comoros",
    code: "KM",
    continent: "Africa",
    country_iso: "COM",
  },
  {
    name: "Congo",
    code: "CG",
    continent: "Africa",
    country_iso: "COG",
  },
  {
    name: "Costa Rica",
    code: "CR",
    continent: "North America",
    country_iso: "CRI",
  },
  {
    name: "Côte d’Ivoire",
    code: "CI",
    continent: "Africa",
    country_iso: "CIV",
  },
  {
    name: "Croatia",
    code: "HR",
    continent: "Europe",
    country_iso: "HRV",
  },
  {
    name: "Cuba",
    code: "CU",
    continent: "North America",
    country_iso: "CUB",
  },
  {
    name: "Curaçao",
    code: "CW",
    continent: "South America",
    country_iso: "CUW",
  },
  {
    name: "Cyprus",
    code: "CY",
    continent: "Asia",
    country_iso: "CYP",
  },
  {
    name: "Czechia",
    code: "CZ",
    continent: "Europe",
    country_iso: "CZE",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    continent: "Africa",
    country_iso: "COD",
  },
  {
    name: "Denmark",
    code: "DK",
    continent: "Europe",
    country_iso: "DNK",
  },
  {
    name: "Djibouti",
    code: "DJ",
    continent: "Africa",
    country_iso: "DJI",
  },
  {
    name: "Dominica",
    code: "DM",
    continent: "North America",
    country_iso: "DMA",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    continent: "North America",
    country_iso: "DOM",
  },
  {
    name: "Ecuador",
    code: "EC",
    continent: "South America",
    country_iso: "ECU",
  },
  {
    name: "Egypt",
    code: "EG",
    continent: "Africa",
    country_iso: "EGY",
  },
  {
    name: "El Salvador",
    code: "SV",
    continent: "North America",
    country_iso: "SLV",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    continent: "Africa",
    country_iso: "GNQ",
  },
  {
    name: "Eritrea",
    code: "ER",
    continent: "Africa",
    country_iso: "ERI",
  },
  {
    name: "Estonia",
    code: "EE",
    continent: "Europe",
    country_iso: "EST",
  },
  {
    name: "Eswatini",
    code: "SZ",
    continent: "Africa",
    country_iso: "SWZ",
  },
  {
    name: "Ethiopia",
    code: "ET",
    continent: "Africa",
    country_iso: "ETH",
  },
  {
    name: "Fiji",
    code: "FJ",
    continent: "Oceania",
    country_iso: "FJI",
  },
  {
    name: "Finland",
    code: "FI",
    continent: "Europe",
    country_iso: "FIN",
  },
  {
    name: "France",
    code: "FR",
    continent: "Europe",
    country_iso: "FRA",
  },
  {
    name: "Gabon",
    code: "GA",
    continent: "Africa",
    country_iso: "GAB",
  },
  {
    name: "Gambia",
    code: "GM",
    continent: "Africa",
    country_iso: "GMB",
  },
  {
    name: "Georgia",
    code: "GE",
    continent: "Asia",
    country_iso: "GEO",
  },
  {
    name: "Germany",
    code: "DE",
    continent: "Europe",
    country_iso: "DEU",
  },
  {
    name: "Ghana",
    code: "GH",
    continent: "Africa",
    country_iso: "GHA",
  },
  {
    name: "Gibraltar",
    code: "GI",
    continent: "Europe",
    country_iso: "GIB",
  },
  {
    name: "Greece",
    code: "GR",
    continent: "Europe",
    country_iso: "GRC",
  },
  {
    name: "Grenada",
    code: "GD",
    continent: "North America",
    country_iso: "GRD",
  },
  {
    name: "Guatemala",
    code: "GT",
    continent: "North America",
    country_iso: "GTM",
  },
  {
    name: "Guinea",
    code: "GN",
    continent: "Africa",
    country_iso: "GIN",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    continent: "Africa",
    country_iso: "GNB",
  },
  {
    name: "Guyana",
    code: "GY",
    continent: "South America",
    country_iso: "GUY",
  },
  {
    name: "Haiti",
    code: "HT",
    continent: "North America",
    country_iso: "HTI",
  },
  {
    name: "Honduras",
    code: "HN",
    continent: "North America",
    country_iso: "HND",
  },
  {
    name: "Hong Kong, China",
    code: "HK",
    continent: "Asia",
    country_iso: "HKG",
  },
  {
    name: "Hungary",
    code: "HU",
    continent: "Europe",
    country_iso: "HUN",
  },
  {
    name: "Iceland",
    code: "IS",
    continent: "Europe",
    country_iso: "ISL",
  },
  {
    name: "India",
    code: "IN",
    continent: "Asia",
    country_iso: "IND",
  },
  {
    name: "Indonesia",
    code: "ID",
    continent: "Asia",
    country_iso: "IDN",
  },
  {
    name: "Iran",
    code: "IR",
    continent: "Asia",
    country_iso: "IRN",
  },
  {
    name: "Iraq",
    code: "IQ",
    continent: "Asia",
    country_iso: "IRQ",
  },
  {
    name: "Ireland",
    code: "IE",
    continent: "Europe",
    country_iso: "IRL",
  },
  {
    name: "Israel",
    code: "IL",
    continent: "Asia",
    country_iso: "ISR",
  },
  {
    name: "Italy",
    code: "IT",
    continent: "Europe",
    country_iso: "ITA",
  },
  {
    name: "Jamaica",
    code: "JM",
    continent: "North America",
    country_iso: "JAM",
  },
  {
    name: "Japan",
    code: "JP",
    continent: "Asia",
    country_iso: "JPN",
  },
  {
    name: "Jordan",
    code: "JO",
    continent: "Asia",
    country_iso: "JOR",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    continent: "Asia",
    country_iso: "KAZ",
  },
  {
    name: "Kenya",
    code: "KE",
    continent: "Africa",
    country_iso: "KEN",
  },
  {
    name: "Kiribati",
    code: "KI",
    continent: "Oceania",
    country_iso: "KIR",
  },
  {
    name: "Democratic People’s Republic of Korea",
    code: "KP",
    continent: "Asia",
    country_iso: "PRK",
  },
  {
    name: "Republic of Korea",
    code: "KR",
    continent: "Asia",
    country_iso: "KOR",
  },
  {
    name: "Kosovo (under UNSCR 1244)",
    code: null,
    continent: null,
    country_iso: null,
  },
  {
    name: "Kuwait",
    code: "KW",
    continent: "Asia",
    country_iso: "KWT",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    continent: "Asia",
    country_iso: "KGZ",
  },
  {
    name: "Lao People’s Democratic Republic",
    code: "LA",
    continent: "Asia",
    country_iso: "LAO",
  },
  {
    name: "Latvia",
    code: "LV",
    continent: "Europe",
    country_iso: "LVA",
  },
  {
    name: "Lebanon",
    code: "LB",
    continent: "Asia",
    country_iso: "LBN",
  },
  {
    name: "Lesotho",
    code: "LS",
    continent: "Africa",
    country_iso: "LSO",
  },
  {
    name: "Liberia",
    code: "LR",
    continent: "Africa",
    country_iso: "LBR",
  },
  {
    name: "Libya",
    code: "LY",
    continent: "Africa",
    country_iso: "LBY",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    continent: "Europe",
    country_iso: "LIE",
  },
  {
    name: "Lithuania",
    code: "LT",
    continent: "Europe",
    country_iso: "LTU",
  },
  {
    name: "Luxembourg",
    code: "LU",
    continent: "Europe",
    country_iso: "LUX",
  },
  {
    name: "Macao, China",
    code: "MO",
    continent: "Asia",
    country_iso: "MAC",
  },
  {
    name: "Madagascar",
    code: "MG",
    continent: "Africa",
    country_iso: "MDG",
  },
  {
    name: "Malawi",
    code: "MW",
    continent: "Africa",
    country_iso: "MWI",
  },
  {
    name: "Maldives",
    code: "MV",
    continent: "Asia",
    country_iso: "MDV",
  },
  {
    name: "Malaysia",
    code: "MY",
    continent: "Asia",
    country_iso: "MYS",
  },
  {
    name: "Mali",
    code: "ML",
    continent: "Africa",
    country_iso: "MLI",
  },
  {
    name: "Malta",
    code: "MT",
    continent: "Europe",
    country_iso: "MLT",
  },
  {
    name: "Marshall islands",
    code: "MH",
    continent: "Oceania",
    country_iso: "MHL",
  },
  {
    name: "Mauritania",
    code: "MR",
    continent: "Africa",
    country_iso: "MRT",
  },
  {
    name: "Mauritius",
    code: "MU",
    continent: "Africa",
    country_iso: "MUS",
  },
  {
    name: "Micronesia (Federated States of)",
    code: "FM",
    continent: "Oceania",
    country_iso: "FSM",
  },
  {
    name: "Mexico",
    code: "MX",
    continent: "North America",
    country_iso: "MEX",
  },
  {
    name: "Republic of Moldova",
    code: "MD",
    continent: "Europe",
    country_iso: "MDA",
  },
  {
    name: "Monaco",
    code: "MC",
    continent: "Europe",
    country_iso: "MCO",
  },
  {
    name: "Mongolia",
    code: "MN",
    continent: "Asia",
    country_iso: "MNG",
  },
  {
    name: "Montenegro",
    code: "ME",
    continent: "Europe",
    country_iso: "MNE",
  },
  {
    name: "Morocco",
    code: "MA",
    continent: "Africa",
    country_iso: "MAR",
  },
  {
    name: "Mozambique",
    code: "MZ",
    continent: "Africa",
    country_iso: "MOZ",
  },
  {
    name: "Myanmar",
    code: "MM",
    continent: "Asia",
    country_iso: "MMR",
  },
  {
    name: "Namibia",
    code: "NA",
    continent: "Africa",
    country_iso: "NAM",
  },
  {
    name: "Nauru",
    code: "NR",
    continent: "Oceania",
    country_iso: "NRU",
  },
  {
    name: "Nepal",
    code: "NP",
    continent: "Asia",
    country_iso: "NPL",
  },
  {
    name: "Netherlands",
    code: "NL",
    continent: "Europe",
    country_iso: "NLD",
  },
  {
    name: "New Zealand",
    code: "NZ",
    continent: "Oceania",
    country_iso: "NZL",
  },
  {
    name: "Nicaragua",
    code: "NI",
    continent: "North America",
    country_iso: "NIC",
  },
  {
    name: "Niger",
    code: "NE",
    continent: "Africa",
    country_iso: "NER",
  },
  {
    name: "Nigeria",
    code: "NG",
    continent: "Africa",
    country_iso: "NGA",
  },
  {
    name: "North Macedonia",
    code: "MK",
    continent: "Europe",
    country_iso: "MKD",
  },
  {
    name: "Norway",
    code: "NO",
    continent: "Europe",
    country_iso: "NOR",
  },
  {
    name: "Oman",
    code: "OM",
    continent: "Asia",
    country_iso: "OMN",
  },
  {
    name: "Pakistan",
    code: "PK",
    continent: "Asia",
    country_iso: "PAK",
  },
  {
    name: "State of Palestine",
    code: "PS",
    continent: "Asia",
    country_iso: "PSE",
  },
  {
    name: "Panama",
    code: "PA",
    continent: "North America",
    country_iso: "PAN",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    continent: "Oceania",
    country_iso: "PNG",
  },
  {
    name: "Palau",
    code: "PW",
    continent: "Oceania",
    country_iso: "PLW",
  },
  {
    name: "Paraguay",
    code: "PY",
    continent: "South America",
    country_iso: "PRY",
  },
  {
    name: "Peru",
    code: "PE",
    continent: "South America",
    country_iso: "PER",
  },
  {
    name: "Philippines",
    code: "PH",
    continent: "Asia",
    country_iso: "PHL",
  },
  {
    name: "Poland",
    code: "PL",
    continent: "Europe",
    country_iso: "POL",
  },
  {
    name: "Portugal",
    code: "PT",
    continent: "Europe",
    country_iso: "PRT",
  },
  {
    name: "Puerto Rico (USA)",
    code: "PR",
    continent: "North America",
    country_iso: "PRI",
  },
  {
    name: "Qatar",
    code: "QA",
    continent: "Asia",
    country_iso: "QAT",
  },
  {
    name: "Romania",
    code: "RO",
    continent: "Europe",
    country_iso: "ROU",
  },
  {
    name: "Russian Federation",
    code: "RU",
    continent: "Europe",
    country_iso: "RUS",
  },
  {
    name: "Rwanda",
    code: "RW",
    continent: "Africa",
    country_iso: "RWA",
  },
  {
    name: "Saint Barthelemy",
    code: "BL",
    continent: "North America",
    country_iso: "BLM",
  },
  {
    name: "Saint Helena",
    code: "SH",
    continent: "Africa",
    country_iso: "SHN",
  },
  {
    name: "Saint Martin",
    code: "MF",
    continent: "Europe",
    country_iso: "MAF",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    continent: "North America",
    country_iso: "SPM",
  },

  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    continent: "North America",
    country_iso: "KNA",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    continent: "North America",
    country_iso: "LCA",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    continent: "North America",
    country_iso: "VCT",
  },

  {
    name: "San Marino",
    code: "SM",
    continent: "Europe",
    country_iso: "SMR",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    continent: "Asia",
    country_iso: "SAU",
  },
  {
    name: "Senegal",
    code: "SN",
    continent: "Africa",
    country_iso: "SEN",
  },
  {
    name: "Serbia",
    code: "RS",
    continent: "Europe",
    country_iso: "SRB",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    continent: "Africa",
    country_iso: "SLE",
  },
  {
    name: "Singapore",
    code: "SG",
    continent: "Asia",
    country_iso: "SGP",
  },
  {
    name: "Sint Maarten",
    code: "SX",
    continent: "North America",
    country_iso: "SXM",
  },
  {
    name: "Slovakia",
    code: "SK",
    continent: "Europe",
    country_iso: "SVK",
  },
  {
    name: "Slovenia",
    code: "SI",
    continent: "Europe",
    country_iso: "SVN",
  },
  {
    name: "Somalia",
    code: "SO",
    continent: "Africa",
    country_iso: "SOM",
  },
  {
    name: "South Africa",
    code: "ZA",
    continent: "Africa",
    country_iso: "ZAF",
  },
  {
    name: "South Sudan",
    code: "SS",
    continent: "Africa",
    country_iso: "SSD",
  },
  {
    name: "Spain",
    code: "ES",
    continent: "Europe",
    country_iso: "ESP",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    continent: "Asia",
    country_iso: "LKA",
  },
  {
    name: "Sudan",
    code: "SD",
    continent: "Africa",
    country_iso: "SDN",
  },
  {
    name: "Suriname",
    code: "SR",
    continent: "South America",
    country_iso: "SUR",
  },
  {
    name: "Sweden",
    code: "SE",
    continent: "Europe",
    country_iso: "SWE",
  },
  {
    name: "Switzerland",
    code: "CH",
    continent: "Europe",
    country_iso: "CHE",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    continent: "Asia",
    country_iso: "SYR",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    continent: "Asia",
    country_iso: "TJK",
  },
  {
    name: "Tanzania",
    code: "TZ",
    continent: "Africa",
    country_iso: "TZA",
  },
  {
    name: "Thailand",
    code: "TH",
    continent: "Asia",
    country_iso: "THA",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    continent: "Asia",
    country_iso: "TLS",
  },
  {
    name: "Togo",
    code: "TG",
    continent: "Africa",
    country_iso: "TGO",
  },
  {
    name: "Tonga",
    code: "TO",
    continent: "Oceania",
    country_iso: "TON",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    continent: "North America",
    country_iso: "TTO",
  },
  {
    name: "Tunisia",
    code: "TN",
    continent: "Africa",
    country_iso: "TUN",
  },
  {
    name: "Turkey",
    code: "TR",
    continent: "Asia",
    country_iso: "TUR",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    continent: "Asia",
    country_iso: "TKM",
  },
  {
    name: "Uganda",
    code: "UG",
    continent: "Africa",
    country_iso: "UGA",
  },
  {
    name: "Ukraine",
    code: "UA",
    continent: "Europe",
    country_iso: "UKR",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    continent: "Asia",
    country_iso: "ARE",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    continent: "Europe",
    country_iso: "GBR",
  },
  {
    name: "United States of America",
    code: "US",
    continent: "North America",
    country_iso: "USA",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    continent: "Oceania",
    country_iso: "UMI",
  },
  {
    name: "United States Virgin Islands",
    code: "VI",
    continent: "North America",
    country_iso: "VIR",
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    continent: "North America",
    country_iso: "VGB",
  },
  {
    name: "Uruguay",
    code: "UY",
    continent: "South America",
    country_iso: "URY",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    continent: "Asia",
    country_iso: "UZB",
  },
  {
    name: "Holy See",
    code: "VA",
    continent: "Europe",
    country_iso: "VAT",
  },
  {
    name: "Venezuela",
    code: "VE",
    continent: "South America",
    country_iso: "VEN",
  },
  {
    name: "Viet Nam",
    code: "VN",
    continent: "Asia",
    country_iso: "VNM",
  },
  {
    name: "Western Sahara",
    code: "EH",
    continent: "Africa",
    country_iso: "ESH",
  },
  {
    name: "Yemen",
    code: "YE",
    continent: "Asia",
    country_iso: "YEM",
  },
  {
    name: "Zambia",
    code: "ZM",
    continent: "Africa",
    country_iso: "ZMB",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    continent: "Africa",
    country_iso: "ZWE",
  },
  {
    name: "Abyei",
    code: null,
    continent: null,
    country_iso: null,
  },
  {
    name: "Seychelles",
    code: "SC",
    continent: "Africa",
    country_iso: "SYC",
  },
  {
    name: "Solomon islands",
    code: "SB",
    continent: "Oceania",
    country_iso: "SLB",
  },
  {
    name: "Solomon islands",
    code: "SB",
    continent: "Oceania",
    country_iso: "SLB",
  },
  {
    name: "Tuvalu",
    code: "TV",
    continent: "Oceania",
    country_iso: "TUV",
  },
  {
    name: "Vanuatu",
    code: "VU",
    continent: "Oceania",
    country_iso: "VUT",
  },

  {
    name: "Samoa",
    code: "WS",
    continent: "Oceania",
    country_iso: "WSM",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    continent: "Africa",
    country_iso: "STP",
  },
];

// // worker functions for temporary use
// const data = []; // enter array to map
// const newCountries = countries.map((country) => {
//   const matchedCountry = data.find(
//     (element) => element.title.trim() === country.name.trim()
//   );
//   return {
//     ...country,
//     country_iso: country?.country_iso || matchedCountry?.field_iso_code || null,
//   };
// });
// console.log({ newCountries });
