const initial = [
  { name: "Aksai Chin", code: null, country_iso: null },
  { name: "Afghanistan", code: "AF", country_iso: "AFG" },
  { name: "Albania", code: "AL", country_iso: "ALB" },
  { name: "Algeria", code: "DZ", country_iso: "DZA" },
  { name: "American Samoa", code: "AS", country_iso: "ASM" },
  { name: "Andorra", code: "AD", country_iso: "AND" },
  { name: "Angola", code: "AO", country_iso: "AGO" },
  { name: "Antigua and Barbuda", code: "AG", country_iso: "ATG" },
  { name: "Argentina", code: "AR", country_iso: "ARG" },
  { name: "Armenia", code: "AM", country_iso: "ARM" },
  { name: "Aruba", code: "AW", country_iso: "ABW" },
  { name: "Australia", code: "AU", country_iso: "AUS" },
  { name: "Austria", code: "AT", country_iso: "AUT" },
  { name: "Azerbaijan", code: "AZ", country_iso: "AZE" },
  { name: "Bahamas", code: "BS", country_iso: "BHS" },
  { name: "Bahrain", code: "BH", country_iso: "BHR" },
  { name: "Bangladesh", code: "BD", country_iso: "BGD" },
  { name: "Barbados", code: "BB", country_iso: "BRB" },
  { name: "Belarus", code: "BY", country_iso: "BLR" },
  { name: "Belgium", code: "BE", country_iso: "BEL" },
  { name: "Belize", code: "BZ", country_iso: "BLZ" },
  { name: "Benin", code: "BJ", country_iso: "BEN" },
  { name: "Bermuda", code: "BM", country_iso: "BMU" },
  { name: "Bhutan", code: "BT", country_iso: "BTN" },
  { name: "Bolivia", code: "BO", country_iso: "BOL" },
  { name: "Bosnia and Herzegovina", code: "BA", country_iso: "BIH" },
  { name: "Botswana", code: "BW", country_iso: "BWA" },
  { name: "Brazil", code: "BR", country_iso: "BRA" },
  { name: "Brunei Darussalam", country_iso: "BRN" },
  { name: "Bulgaria", code: "BG", country_iso: "BGR" },
  { name: "Burkina Faso", code: "BF", country_iso: "BFA" },
  { name: "Burundi", code: "BI", country_iso: "BDI" },
  { name: "Cambodia", code: "KH", country_iso: "KHM" },
  { name: "Cameroon", code: "CM", country_iso: "CMR" },
  { name: "Canada", code: "CA", country_iso: "CAN" },
  { name: "Cabo Verde", code: "CV", country_iso: "CPV" },
  { name: "Cayman Islands", code: "KY", country_iso: "CYM" },
  { name: "Central African Republic", code: "CF", country_iso: "CAF" },
  { name: "Chad", code: "TD", country_iso: "TCD" },
  { name: "Chile", code: "CL", country_iso: "CHL" },
  { name: "China", code: "CN", country_iso: "CHN" },
  { name: "Colombia", code: "CO", country_iso: "COL" },
  { name: "Comoros", code: "KM", country_iso: "COM" },
  { name: "Congo", code: "CG", country_iso: "COG" },
  { name: "Costa Rica", code: "CR", country_iso: "CRI" },
  { name: "Côte d’Ivoire", code: "CI", country_iso: "CIV" },
  { name: "Croatia", code: "HR", country_iso: "HRV" },
  { name: "Cuba", code: "CU", country_iso: "CUB" },
  { name: "Curaçao", code: "CW", country_iso: "CUW" },
  { name: "Cyprus", code: "CY", country_iso: "CYP" },
  { name: "Czechia", code: "CZ", country_iso: "CZE" },
  { name: "Democratic Republic of the Congo", code: "CD", country_iso: "COD" },
  { name: "Denmark", code: "DK", country_iso: "DNK" },
  { name: "Djibouti", code: "DJ", country_iso: "DJI" },
  { name: "Dominica", code: "DM", country_iso: "DMA" },
  { name: "Dominican Republic", code: "DO", country_iso: "DOM" },
  { name: "Ecuador", code: "EC", country_iso: "ECU" },
  { name: "Egypt", code: "EG", country_iso: "EGY" },
  { name: "El Salvador", code: "SV", country_iso: "SLV" },
  { name: "Equatorial Guinea", code: "GQ", country_iso: "GNQ" },
  { name: "Eritrea", code: "ER", country_iso: "ERI" },
  { name: "Estonia", code: "EE", country_iso: "EST" },
  { name: "Eswatini", code: "SZ", country_iso: "SWZ" },
  { name: "Ethiopia", code: "ET", country_iso: "ETH" },
  { name: "Fiji", code: "FJ", country_iso: "FJI" },
  { name: "Finland", code: "FI", country_iso: "FIN" },
  { name: "France", code: "FR", country_iso: "FRA" },
  { name: "Gabon", code: "GA", country_iso: "GAB" },
  { name: "Gambia", code: "GM", country_iso: "GMB" },
  { name: "Georgia", code: "GE", country_iso: "GEO" },
  { name: "Germany", code: "DE", country_iso: "DEU" },
  { name: "Ghana", code: "GH", country_iso: "GHA" },
  { name: "Gibraltar", code: "GI", country_iso: "GIB" },
  { name: "Greece", code: "GR", country_iso: "GRC" },
  { name: "Grenada", code: "GD", country_iso: "GRD" },
  { name: "Guatemala", code: "GT", country_iso: "GTM" },
  { name: "Guinea", code: "GN", country_iso: "GIN" },
  { name: "Guinea-Bissau", code: "GW", country_iso: "GNB" },
  { name: "Guyana", code: "GY", country_iso: "GUY" },
  { name: "Haiti", code: "HT", country_iso: "HTI" },
  { name: "Honduras", code: "HN", country_iso: "HND" },
  { name: "Hong Kong, China", code: "HK", country_iso: "HKG" },
  { name: "Hungary", code: "HU", country_iso: "HUN" },
  { name: "Iceland", code: "IS", country_iso: "ISL" },
  { name: "India", code: "IN", country_iso: "IND" },
  { name: "Indonesia", code: "ID", country_iso: "IDN" },
  { name: "Iran", code: "IR", country_iso: "IRN" },
  { name: "Iraq", code: "IQ", country_iso: "IRQ" },
  { name: "Ireland", code: "IE", country_iso: "IRL" },
  { name: "Israel", code: "IL", country_iso: "ISR" },
  { name: "Italy", code: "IT", country_iso: "ITA" },
  { name: "Jamaica", code: "JM", country_iso: "JAM" },
  { name: "Japan", code: "JP", country_iso: "JPN" },
  { name: "Jordan", code: "JO", country_iso: "JOR" },
  { name: "Kazakhstan", code: "KZ", country_iso: "KAZ" },
  { name: "Kenya", code: "KE", country_iso: "KEN" },
  {
    name: "Kiribati",
    code: "KI",
    country_iso: "KIR",
  },
  {
    name: "Democratic People’s Republic of Korea",
    code: "KP",
    country_iso: "PRK",
  },
  { name: "Republic of Korea", code: "KR", country_iso: "KOR" },
  { name: "Kosovo (under UNSCR 1244)", code: null, country_iso: null },
  { name: "Kuwait", code: "KW", country_iso: "KWT" },
  { name: "Kyrgyzstan", code: "KG", country_iso: "KGZ" },
  { name: "Lao People’s Democratic Republic", code: "LA", country_iso: "LAO" },
  { name: "Latvia", code: "LV", country_iso: "LVA" },
  { name: "Lebanon", code: "LB", country_iso: "LBN" },
  { name: "Lesotho", code: "LS", country_iso: "LSO" },
  { name: "Liberia", code: "LR", country_iso: "LBR" },
  { name: "Libya", code: "LY", country_iso: "LBY" },
  { name: "Liechtenstein", code: "LI", country_iso: "LIE" },
  { name: "Lithuania", code: "LT", country_iso: "LTU" },
  { name: "Luxembourg", code: "LU", country_iso: "LUX" },
  { name: "Macao, China", code: "MO", country_iso: "MAC" },
  { name: "Madagascar", code: "MG", country_iso: "MDG" },
  { name: "Malawi", code: "MW", country_iso: "MWI" },
  {
    name: "Maldives",
    code: "MV",
    country_iso: "MDV",
  },
  { name: "Malaysia", code: "MY", country_iso: "MYS" },
  { name: "Mali", code: "ML", country_iso: "MLI" },
  { name: "Malta", code: "MT", country_iso: "MLT" },
  {
    name: "Marshall islands",
    code: "MH",
    country_iso: "MHL",
  },
  { name: "Mauritania", code: "MR", country_iso: "MRT" },
  { name: "Mauritius", code: "MU", country_iso: "MUS" },
  {
    name: "Micronesia (Federated States of)",
    code: "FM",
    country_iso: "FSM",
  },
  { name: "Mexico", code: "MX", country_iso: "MEX" },
  { name: "Republic of Moldova", code: "MD", country_iso: "MDA" },
  { name: "Monaco", code: "MC", country_iso: "MCO" },
  { name: "Mongolia", code: "MN", country_iso: "MNG" },
  { name: "Montenegro", code: "ME", country_iso: "MNE" },
  { name: "Morocco", code: "MA", country_iso: "MAR" },
  { name: "Mozambique", code: "MZ", country_iso: "MOZ" },
  { name: "Myanmar", code: "MM", country_iso: "MMR" },
  { name: "Namibia", code: "NA", country_iso: "NAM" },
  { name: "Nauru", code: "NR", country_iso: "NRU" },
  { name: "Nepal", code: "NP", country_iso: "NPL" },
  { name: "Netherlands", code: "NL", country_iso: "NLD" },
  { name: "New Zealand", code: "NZ", country_iso: "NZL" },
  { name: "Nicaragua", code: "NI", country_iso: "NIC" },
  { name: "Niger", code: "NE", country_iso: "NER" },
  { name: "Nigeria", code: "NG", country_iso: "NGA" },
  { name: "North Macedonia", code: "MK", country_iso: "MKD" },
  { name: "Norway", code: "NO", country_iso: "NOR" },
  { name: "Oman", code: "OM", country_iso: "OMN" },
  { name: "Pakistan", code: "PK", country_iso: "PAK" },
  { name: "State of Palestine", code: "PS", country_iso: "PSE" },
  { name: "Panama", code: "PA", country_iso: "PAN" },
  { name: "Papua New Guinea", code: "PG", country_iso: "PNG" },
  {
    name: "Palau",
    code: "PW",
    country_iso: "PLW",
  },
  { name: "Paraguay", code: "PY", country_iso: "PRY" },
  { name: "Peru", code: "PE", country_iso: "PER" },
  { name: "Philippines", code: "PH", country_iso: "PHL" },
  { name: "Poland", code: "PL", country_iso: "POL" },
  { name: "Portugal", code: "PT", country_iso: "PRT" },
  { name: "Puerto Rico (USA)", code: "PR", country_iso: "PRI" },
  { name: "Qatar", code: "QA", country_iso: "QAT" },
  { name: "Romania", code: "RO", country_iso: "ROU" },
  { name: "Russian Federation", code: "RU", country_iso: "RUS" },
  { name: "Rwanda", code: "RW", country_iso: "RWA" },
  { name: "Saint Barthelemy", code: "BL", country_iso: "BLM" },
  { name: "Saint Helena", code: "SH", country_iso: "SHN" },
  { name: "Saint Martin", code: "MF", country_iso: "MAF" },
  { name: "Saint Pierre and Miquelon", code: "PM", country_iso: "SPM" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    country_iso: "KNA",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    country_iso: "LCA",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    country_iso: "VCT",
  },
  { name: "San Marino", code: "SM", country_iso: "SMR" },
  { name: "Saudi Arabia", code: "SA", country_iso: "SAU" },
  { name: "Senegal", code: "SN", country_iso: "SEN" },
  { name: "Serbia", code: "RS", country_iso: "SRB" },
  { name: "Sierra Leone", code: "SL", country_iso: "SLE" },
  { name: "Singapore", code: "SG", country_iso: "SGP" },
  { name: "Sint Maarten", code: "SX", country_iso: "SXM" },
  { name: "Slovakia", code: "SK", country_iso: "SVK" },
  { name: "Slovenia", code: "SI", country_iso: "SVN" },
  { name: "Somalia", code: "SO", country_iso: "SOM" },
  { name: "South Africa", code: "ZA", country_iso: "ZAF" },
  { name: "South Sudan", code: "SS", country_iso: "SSD" },
  { name: "Spain", code: "ES", country_iso: "ESP" },
  { name: "Sri Lanka", code: "LK", country_iso: "LKA" },
  { name: "Sudan", code: "SD", country_iso: "SDN" },
  { name: "Suriname", code: "SR", country_iso: "SUR" },
  { name: "Sweden", code: "SE", country_iso: "SWE" },
  { name: "Switzerland", code: "CH", country_iso: "CHE" },
  { name: "Syrian Arab Republic", code: "SY", country_iso: "SYR" },
  { name: "Tajikistan", code: "TJ", country_iso: "TJK" },
  { name: "Tanzania", code: "TZ", country_iso: "TZA" },
  { name: "Thailand", code: "TH", country_iso: "THA" },
  { name: "Timor-Leste", code: "TL", country_iso: "TLS" },
  { name: "Togo", code: "TG", country_iso: "TGO" },
  { name: "Trinidad and Tobago", code: "TT", country_iso: "TTO" },
  { name: "Tunisia", code: "TN", country_iso: "TUN" },
  { name: "Turkey", code: "TR", country_iso: "TUR" },
  { name: "Turkmenistan", code: "TM", country_iso: "TKM" },
  { name: "Uganda", code: "UG", country_iso: "UGA" },
  { name: "Ukraine", code: "UA", country_iso: "UKR" },
  { name: "United Arab Emirates", code: "AE", country_iso: "ARE" },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    country_iso: "GBR",
  },
  { name: "United States of America", code: "US", country_iso: "USA" },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    country_iso: "UMI",
  },
  { name: "United States Virgin Islands", code: "VI", country_iso: "VIR" },
  { name: "British Virgin Islands", code: "VG", country_iso: "VGB" },
  { name: "Uruguay", code: "UY", country_iso: "URY" },
  { name: "Uzbekistan", code: "UZ", country_iso: "UZB" },
  { name: "Holy See", code: "VA", country_iso: "VAT" },
  { name: "Venezuela", code: "VE", country_iso: "VEN" },
  { name: "Viet Nam", code: "VN", country_iso: "VNM" },
  { name: "Western Sahara", code: "EH", country_iso: "ESH" },
  { name: "Yemen", code: "YE", country_iso: "YEM" },
  { name: "Zambia", code: "ZM", country_iso: "ZMB" },
  { name: "Zimbabwe", code: "ZW", country_iso: "ZWE" },
  { name: "Abyei", code: null, country_iso: null },
  {
    name: "Seychelles",
    code: "SC",
    country_iso: "SYC",
  },
  {
    name: "Solomon islands",
    code: "SB",
    country_iso: "SLB",
  },
  {
    name: "Solomon islands",
    code: "SB",
    country_iso: "SLB",
  },
  {
    name: "Tuvalu",
    code: "TV",
    country_iso: "TUV",
  },
  {
    name: "Vanuatu",
    code: "VU",
    country_iso: "VUT",
  },
  {
    name: "Samoa",
    code: "WS",
    country_iso: "WSM",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    country_iso: "STP",
  },
];

const features = []; // insert features array from geo.json
